services:
  - type: web
    name: job-scheduler-api
    env: docker
    dockerfilePath: ./Dockerfile
    preDeployCommand: "python init_db.py"
    dockerCommand: "uvicorn api.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: job-scheduler-db
          property: connectionString

  - type: worker
    name: job-scheduler-worker
    env: docker
    dockerfilePath: ./Dockerfile
    dockerCommand: "python worker/worker.py"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: job-scheduler-db
          property: connectionString

  - type: worker
    name: job-scheduler-watchdog
    env: docker
    dockerfilePath: ./Dockerfile
    dockerCommand: "python worker/watchdog.py"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: job-scheduler-db
          property: connectionString

databases:
  - name: job-scheduler-db
    databaseName: job_scheduler
    plan: free
